logging:
  level:
    net.ttddyy.dsproxy.listener: debug

spring:
  cloud:
    stream:
      bindings:
        pay-out-0:
          destination: pay
          binder: kafka
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3311/productdb
    username: ${db_username}
    password: ${db_password}
  jpa:
#    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB106Dialect
#    show-sql: true
  liquibase:
    change-log: classpath:/master/changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9990/realms/Product/protocol/openid-connect/certs
#    enabled: false